In [1]:
import numpy as np
def quadratic_soln(a,b,c):
    x1=(-b+np.sqrt(b**2-4*a*c))/(2*a)
    x2=(-b-np.sqrt(b**2-4*a*c))/(2*a)
    return x1,x2


single_solution=lambda a,b,c:quadratic_solution_single(a,b,c)
def quadratic_soln_single(a,b,c):
    [x1,x2]=quadratic_soln(a,b,c)
    if x1>=x2:
        solution=x1
    else:
        solution=x2
    return solution


In [2]:
hhh=lambda a,b,c:quadratic_soln_single(a,b,c)

x1

In [3]:
x1=quadratic_soln(1,3,2)

In [4]:
x1

(-1.0, -2.0)

In [5]:
[x1,x2]=quadratic_soln(3,8,2)

In [6]:
x1


-0.2792407799438735

In [7]:
x2

-2.3874258867227933

In [8]:
lambda

SyntaxError: invalid syntax (<ipython-input-8-444025390096>, line 1)

In [ ]:
single_solution(5,40,20)

In [ ]:
hhh(5,40,20)

In [9]:
# (2)
def sphere(r):
    Area=4*np.pi*r**2
    Volume=4/3*np.pi*r**3
    return Area,Volume

In [11]:
sphere(10)

(1256.6370614359173, 4188.790204786391)

In [12]:
[Area,Volume]=sphere(10)
print('The Area is ',Area,' , the Volume is ',Volume,'.')

The Area is  1256.6370614359173  , the Volume is  4188.790204786391 .


In [13]:
# (3)
def myfunc(x):
    sum=0
    if x<=0:
        print('x is not positive.')
    else:
        for i in range(0,x+1):
            sum=sum+np.sqrt(i)
    return sum

In [14]:
myfunc(5)

8.382332347441762

In [15]:
myfunc(1)

1.0

In [16]:
myfunc(2)

2.414213562373095

In [22]:
# (4)
def taylor(x):
    exp_ax=0
    for i in range(0,10):
        exp_ax=exp_ax+x**i/np.math.factorial(i)
    exp_x=np.exp(x)
    err=exp_ax-exp_x
    return exp_x,exp_ax,err

In [23]:
taylor(1)

(2.718281828459045, 2.7182815255731922, -3.0288585284310443e-07)

In [24]:
taylor(0.1)

(1.1051709180756477, 1.1051709180756473, -4.440892098500626e-16)

In [25]:
taylor(0.5)

(1.6487212707001282, 1.648721270418251, -2.818771882573401e-10)

In [26]:
taylor(20)

(485165195.4097903, 2423600.1887125224, -482741595.22107774)

In [27]:
# (5)
def sine(x):
    sine_ax=0
    for i in range(0,10):
        sine_ax=sine_ax+(-1)**i*x**(2*i+1)/np.math.factorial(2*i+1)
    sine_x=np.sin(x)
    err=np.abs(sine_x-sine_ax)
    return sine_ax,sine_x,err

In [28]:
sine(np.pi)

(-5.28918280357759e-10, 1.2246467991473532e-16, 5.289184028224389e-10)

In [29]:
sine(0.1)

(0.09983341664682817, 0.09983341664682815, 1.3877787807814457e-17)

In [30]:
sine(0.5)

(0.479425538604203, 0.479425538604203, 0.0)

In [31]:
sine(1)

(0.8414709848078965, 0.8414709848078965, 0.0)

In [32]:
sine(3.14)

(0.001592652393160744, 0.0015926529164868282, 5.233260842903154e-10)

In [34]:
sine(1.67)
np.zeros(1,5)

TypeError: data type not understood

In [42]:
np.ones((2,5))


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [78]:
# (7)
def fibo(n):
    numb=np.ones(n)
    if n==1:
        return numb[0]
    elif n==2:
        return numb[1]
    else:
        numb[0]=1
        numb[1]=1
        for i in range(2,n):
            numb[i]=numb[i-2]+numb[i-1]
    return numb[n-1]
OG=3
Gold=(1+np.sqrt(5))/2
R_gold=fibo(OG)/fibo(OG-1)
while np.abs(R_gold-Gold)>10**-6:
    OG=OG+1
    R_gold=fibo(OG)/fibo(OG-1)


In [74]:
fibo(1)

1.0

In [60]:
fibo(10)

(55.0, array([ 1.,  1.,  2.,  3.,  5.,  8., 13., 21., 34., 55.]))

In [56]:
fibo(3)

2.0

In [57]:
fibo(4)

3.0

In [70]:
R_gold

array([2., 2.])

In [71]:
fibo(3)

2.0

In [72]:
fibo(2)

array([1., 1.])

In [75]:
fibo(2)

1.0

In [79]:
OG

17

In [80]:
fibo(17)/fibo(16)

1.618034447821682